import type { AnalysisResult, Binding, Conflict } from './types';
import { naturalCompare } from './utils';

function bindingMap(result: AnalysisResult): Map<string, Binding> {
  return new Map(result.bindings.map((binding) => [binding.id, binding]));
}

function location(binding: Binding): string {
  return binding.location.line
    ? `${binding.location.file}:${binding.location.line}`
    : binding.location.file;
}

export function renderTextReport(result: AnalysisResult): string {
  const lines = [
    `Keybind Doctor ${result.toolVersion}`,
    `Platform: ${result.platform}`,
    `Files: ${result.summary.files} | Bindings: ${result.summary.bindings}`,
    `Conflicts: ${result.conflicts.length} (definite ${result.summary.definite}, shadow ${result.summary.shadow}, potential ${result.summary.potential}, reserved ${result.summary.reserved})`,
    `Repair suggestions: ${result.summary.suggestions} | Unresolved: ${result.summary.unresolved}`,
  ];
  const byId = bindingMap(result);
  if (result.conflicts.length === 0) {
    lines.push('', 'No conflicts found.');
  } else {
    lines.push('', 'Findings');
    result.conflicts.forEach((conflict, index) => {
      lines.push(
        `${index + 1}. [${conflict.severity.toUpperCase()}] ${conflict.kind}: ${conflict.key}`,
        `   ${conflict.title}. ${conflict.explanation}`,
      );
      for (const id of conflict.bindingIds) {
        const binding = byId.get(id);
        if (binding) {
          lines.push(
            `   - ${binding.application}: ${binding.command} (${location(binding)})`,
          );
        }
      }
    });
  }
  if (result.suggestions.length > 0) {
    lines.push('', 'Minimum-change plan');
    for (const suggestion of result.suggestions) {
      const binding = byId.get(suggestion.bindingId);
      lines.push(
        `- ${binding?.application ?? suggestion.bindingId}: ${suggestion.from} -> ${suggestion.to} (cost ${suggestion.cost})`,
        `  ${suggestion.reason}`,
      );
    }
  }
  if (result.warnings.length > 0) {
    lines.push('', 'Warnings', ...result.warnings.map((warning) => `- ${warning}`));
  }
  return `${lines.join('\n')}\n`;
}

export function renderMarkdownReport(result: AnalysisResult): string {
  const byId = bindingMap(result);
  const lines = [
    '# Keybind Doctor report',
    '',
    `Generated by Keybind Doctor ${result.toolVersion} for **${result.platform}**.`,
    '',
    '## Summary',
    '',
    '| Files | Bindings | Definite | Shadow | Potential | Reserved | Suggestions | Unresolved |',
    '| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    `| ${result.summary.files} | ${result.summary.bindings} | ${result.summary.definite} | ${result.summary.shadow} | ${result.summary.potential} | ${result.summary.reserved} | ${result.summary.suggestions} | ${result.summary.unresolved} |`,
    '',
    '## Findings',
    '',
  ];
  if (result.conflicts.length === 0) {
    lines.push('No conflicts found.', '');
  } else {
    result.conflicts.forEach((conflict, index) => {
      lines.push(
        `### ${index + 1}. ${conflict.key}: ${conflict.title}`,
        '',
        `**${conflict.severity.toUpperCase()} · ${conflict.kind}**. ${conflict.explanation}`,
        '',
      );
      for (const id of conflict.bindingIds) {
        const binding = byId.get(id);
        if (binding) {
          lines.push(
            `- **${binding.application}**: \`${binding.command}\` in \`${location(binding)}\``,
          );
        }
      }
      lines.push('');
    });
  }
  lines.push('## Minimum-change repair plan', '');
  if (result.suggestions.length === 0) {
    lines.push('No remaps are needed or no safe bounded suggestion was available.', '');
  } else {
    for (const suggestion of result.suggestions) {
      const binding = byId.get(suggestion.bindingId);
      lines.push(
        `- **${binding?.application ?? suggestion.bindingId}**: \`${suggestion.from}\` → \`${suggestion.to}\` (cost ${suggestion.cost}). ${suggestion.reason}`,
      );
    }
    lines.push('');
  }
  if (result.safeReuses.length > 0) {
    lines.push('## Proven safe reuse', '');
    for (const reuse of result.safeReuses) {
      lines.push(`- \`${reuse.key}\`: ${reuse.reason}`);
    }
    lines.push('');
  }
  if (result.warnings.length > 0) {
    lines.push('## Parse warnings', '', ...result.warnings.map((warning) => `- ${warning}`), '');
  }
  return lines.join('\n');
}

function csvCell(value: string | number): string {
  const text = String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function renderCsvReport(result: AnalysisResult): string {
  const byId = bindingMap(result);
  const rows = [
    [
      'conflict_id',
      'kind',
      'severity',
      'key',
      'application',
      'command',
      'file',
      'line',
      'suggested_key',
    ],
  ];
  const suggestionByBinding = new Map(
    result.suggestions.map((suggestion) => [suggestion.bindingId, suggestion]),
  );
  for (const conflict of result.conflicts) {
    for (const id of conflict.bindingIds) {
      const binding = byId.get(id);
      if (!binding) continue;
      rows.push([
        conflict.id,
        conflict.kind,
        conflict.severity,
        conflict.key,
        binding.application,
        binding.command,
        binding.location.file,
        String(binding.location.line ?? ''),
        suggestionByBinding.get(id)?.to ?? '',
      ]);
    }
  }
  return `${rows.map((row) => row.map(csvCell).join(',')).join('\n')}\n`;
}

export function renderJsonReport(result: AnalysisResult): string {
  return `${JSON.stringify(sortResult(result), null, 2)}\n`;
}

function sortResult(result: AnalysisResult): AnalysisResult {
  return {
    ...result,
    bindings: [...result.bindings].sort((left, right) => naturalCompare(left.id, right.id)),
    conflicts: [...result.conflicts].sort((left, right) => naturalCompare(left.id, right.id)),
    safeReuses: [...result.safeReuses].sort((left, right) => naturalCompare(left.key, right.key)),
    suggestions: [...result.suggestions].sort((left, right) =>
      naturalCompare(left.bindingId, right.bindingId),
    ),
    unresolved: [...result.unresolved].sort((left, right) =>
      naturalCompare(left.conflictId, right.conflictId),
    ),
    warnings: [...result.warnings].sort(naturalCompare),
  };
}

export function conflictsAtOrAbove(
  result: AnalysisResult,
  threshold: 'definite' | 'potential' | 'none',
): Conflict[] {
  if (threshold === 'none') return [];
  if (threshold === 'potential') return result.conflicts;
  return result.conflicts.filter(
    (conflict) =>
      conflict.kind === 'definite' ||
      conflict.kind === 'shadow' ||
      (conflict.kind === 'reserved' && conflict.severity === 'high'),
  );
}
